version: '3.8'

services:
  app:
    image: "azer775/gestionsinistre:1.0.1"
    container_name: app_container
    network_mode: "bridge"
    ports:
      - "8089:8089"
    #restart: "always"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/stagedb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    
  db:
    image: mysql:8.0.3
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_PASSWORD: root
      MYSQL_DATABASE: stagedb
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_ROOT_HOST: "%"
    #volumes:
     # - mysql_data:/var/lib/mysql
    #adminer:
     # image: adminer
      #restart: always
      #port:
       # - 9000:8000

#volumes:
 # mysql_data:

