version: '3.8'

services:
  app:
    image: "azer775/gestionsinistre:1.0.1"
    container_name: app_container
    ports:
      - "8089:8089"
    #restart: "always"
    
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_container
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: StageDB
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    #volumes:
     # - mysql_data:/var/lib/mysql
    #adminer:
     # image: adminer
      #restart: always
      #port:
       # - 9000:8000

#volumes:
 # mysql_data:

